name: Build/test

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev"]

jobs:
  build-bootplot:
    permissions: write-all
    name: Build bootplot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine pytest
          python -m build
          twine check --strict dist/*
          
      - name: Install bootplot from the wheel file
        run: |
          pip install dist/*.whl
          
      - name: List the installed packages
        run: |
          pip freeze
      
      - name: Run tests
        run: |
          pytest
